### ISSUE TITLE
Exponentiation::getCommonVars not ready

### ISSUE THREAD

**Issue by weibingrong** [ohhmm/openmind#106]
```
#include "omnn/math/System.h"

int main()
{
    auto& a = "a"_va;
    omnn::math::System s;
    s << a + (a^2);
}
```
returns
Balancing ((a^2) + a)
openmind-0.28-beta1\omnn\math\Exponentiation.cpp:976 (a^2) Exponentiation::getCommonVars not ready

**Comment by ohhmm** [comment]
Please, confirm that it fixed or provide additional details on compiler/platform used if its not. Thanks.

**Comment by weibingrong** [comment]
I just tried 0.28-beta2 and this problem was fixed.
But there is another "cannot dereference end map/set iterator" issue on MSVC.

Thanks

**Comment by ohhmm** [comment]
How to reproduce?

**Comment by ohhmm** [comment]
Most likely the issue with caching on for deserialization of cached values with empty variables-mapping fixed in https://github.com/ohhmm/openmind/releases/tag/0.28-beta3

**Comment by ohhmm** [comment]
https://github.com/ohhmm/openmind/releases/tag/0.28-beta4
