### ISSUE TITLE
Tan

### ISSUE THREAD

**Issue by ohhmm** [ohhmm/openmind#21]
There is a feature request for Tan.
It seem most applicable to do it using constants i and e:
![image](https://user-images.githubusercontent.com/190779/85288678-c7509180-b49e-11ea-894a-1e8c4feee3b2.jpeg)

**Comment by leannejdong** [comment]
these formulae look normal to me. Where exactly in the codes need help?

**Comment by ohhmm** [comment]
The best place would be right between exponentiation operator^= and diffirentiation method d here https://github.com/ohhmm/openmind/blob/2ba79fbf4dcd3e91e9abc18cb6d003e67b0cfcc3/omnn/math/Valuable.h#L220

**Comment by ohhmm** [comment]
A little note about the method naming convention in this project:
If a class method modifies itself object then it should be named starting from small letter and words separated with underscores.
Otherwise if it const method which returns result by value then CamelCaseNamingNoUnderscoresPlease.

**Comment by ohhmm** [comment]
Optimizations
 ![image](https://user-images.githubusercontent.com/190779/127105958-e218720c-016f-45cc-ae8e-00663375192e.jpeg)
